### ISSUE TITLE
build failing on heroku

### ISSUE THREAD

**Issue by JustinM1** [siemensikkema/vapor-jwt#11]
remote: Linking ./.build/release/App
remote: /tmp/build_9e6662da1ad3a4a4089c8520505ca138/.build/release/App.build/Droplet+Setup.swift.o:/tmp/build_9e6662da1ad3a4a4089c8520505ca138/.build/release/App.build/Misc/String+E164Format.swift.o:function _::_TTSf4g_n_n___TFC3App14AuthMiddleware7respondfzT2toC4HTTP7Request10chainingToPS1_9Responder(Response) static const: error: undefined reference to '_TFE8VaporJWTPS_16ClaimsVerifiable12verifyClaimsfGSaPS_5Claim(bool) static'
remote: /tmp/build_9e6662da1ad3a4a4089c8520505ca138/.build/release/App.build/Droplet+Setup.swift.o:/tmp/build_9e6662da1ad3a4a4089c8520505ca138/.build/release/App.build/Misc/String+E164Format.swift.o:function _::_TTSf4g_n_n___TFC3App14AuthMiddleware7respondfzT2toC4HTTP7Request10chainingToPS1_9Responder(Response) static const: error: undefined reference to '_TFE8VaporJWTPS_16ClaimsVerifiable12verifyClaimsfGSaPS_5Claim(bool) static'
remote: /tmp/build_9e6662da1ad3a4a4089c8520505ca138/.build/release/App.build/RenewalTokenMiddleware.swift.o:/tmp/build_9e6662da1ad3a4a4089c8520505ca138/.build/release/App.build/Misc/String+E164Format.swift.o:function _::_TTSf4g_n_n___TFC3App22RenewalTokenMiddleware7respondfzT2toC4HTTP7Request10chainingToPS1_9Responder(Response) static const: error: undefined reference to '_TFE8VaporJWTPS_16ClaimsVerifiable12verifyClaimsfGSaPS_5Claim(bool) static'
remote: clang-3.7: error: linker command failed with exit code 1 (use -v to see invocation)
remote: <unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
remote: <unknown>:0: error: build had 1 command failures

it runs locally on mac with no issue, any ideas?

**Comment by siemensikkema** [comment]
@JustinM1 sorry about the late reply! This is an issue that seems to keep coming up but it should be fixed in 0.6.1. Can you confirm your app or a dependent is not depending on an earlier version?

**Comment by JustinM1** [comment]
@siemensikkema no prob. I know how it can be, especially around this time of year. Unfortunately, I think there is still an issue. 
<img width="456" alt="vapor-jwt_version" src="https://cloud.githubusercontent.com/assets/18277828/21504590/3b5ae8a8-cc2e-11e6-9606-2e2a22cc2986.png">
<img width="822" alt="heroku_builderror" src="https://cloud.githubusercontent.com/assets/18277828/21504598/4f9f7b4e-cc2e-11e6-95f3-22ed54d78cb5.png">

**Comment by siemensikkema** [comment]
Is this on a custom server? How are you building? Can you replicate this on your own machine? I see you're running swift 3.0.1, I doubt upgrading to 3.0.2 will help but it's worth a try.
